version: '3'

services:
    nginx:
      image: nginx
      container_name: nginx
      env_file:
        - .env
      build : requirements/nginx
      ports:
      - 443:443
      restart: always
      depends_on:
      - wordpress
      networks:
      - inception
      volumes:
      - wp-vol:/var/www/html/wordpress

    mariadb:
      image: mariadb
      container_name: mariadb
      build   :
        context: requirements/mariadb
        args:
          SQL_DATABASE: ${SQL_DATABASE}
          SQL_USER: ${SQL_USER}
          SQL_PASSWORD: ${SQL_PASSWORD}
          SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      volumes:
        - db-volume:/var/lib/mysql
      restart : always
      networks:
      - inception

    wordpress:
      container_name: wordpress
      image : wordpress
      env_file:
        - .env
      build: 
        context: requirements/wordpress
      restart : always
      depends_on:
      - mariadb
      volumes:
        - wp-vol:/var/www/html/wordpress
      networks:
      - inception
  
networks:
  inception:
    driver: bridge

volumes:
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb
  wp-vol:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress